---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: "Miztiik Incident Response Template"

Parameters:
  enableDEBUGGER:
    Description: Do you want to enable logging.
    Default: "False"
    Type: String
    AllowedValues: ["True", "False"]
    ConstraintDescription: Must be boolean.

  SecurityContactEmail:
    Description: Email address to receive notifications. Must be a valid email address.
    Default: "youremail@example.com"
    Type: String
    AllowedPattern: ^(?:[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])$

  FunctionNameSuffix:
    Description: 'Suffix to append to the Lambda functions.'
    Type: 'String'
    Default: '-Miztiik-InfoSec'

Globals:
  Function:
    Runtime: python3.7
    Timeout: 10
    Tracing: Active
    MemorySize: 128
    Environment:
      Variables:
        DEBUG_MODE:
          Ref: enableDEBUGGER
    Tags:
      Organisation: Miztiik-InfoSec

Resources:

  ec2InstanceQuarantineFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: 'Attaches the instance a SG with no rules so it cannott communicate with the outside world'
      FunctionName: !Sub 'ec2InstanceQuarantineFn${FunctionNameSuffix}'
      Handler: ec2_instance_quarantine.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambda_src/ec2_instance_quarantine.py
      Environment:
        Variables:
          ENABLE_DEBUG:
            Ref: enableDEBUGGER
      MemorySize: 128
      Timeout: 15
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn

  ec2InstanceSnapshotFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: 'Takes a snapshot of the given instance ID'
      FunctionName: !Sub 'ec2InstanceSnapshotFn${FunctionNameSuffix}'
      Handler: ec2_instance_snapshot.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambda_src/ec2_instance_snapshot.py
      Environment:
        Variables:
          ENABLE_DEBUG:
            Ref: enableDEBUGGER
      MemorySize: 128
      Timeout: 180
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn

  incidentResponseStepFunction:
    Type: AWS::StepFunctions::StateMachine
    DependsOn: StatesExecutionRole
    Properties:
      StateMachineName: !Sub 'incidentResponseStepFunction${FunctionNameSuffix}'
      RoleArn:
        Fn::GetAtt:
        - StatesExecutionRole
        - Arn
      DefinitionString: !Sub |
        {
          "Comment": "Isolate compromised EC2 Instance & Snapshot for Investigation",
          "StartAt": "ec2IncidentResponse",
          "States": {
            "ec2IncidentResponse": {
              "Type": "Parallel",
              "End": true,
              "Branches": [
                {
                  "StartAt": "ec2InstanceSnapshot",
                  "States": {
                    "ec2InstanceSnapshot": {
                      "Type": "Task",
                      "Resource": "${ec2InstanceSnapshotFn.Arn}",
                      "End": true,
                      "Retry": [
                        {
                          "ErrorEquals": [
                            "States.ALL"
                          ],
                          "IntervalSeconds": 1,
                          "MaxAttempts": 3,
                          "BackoffRate": 2
                        }
                      ]
                    }
                  }
                },
                {
                  "StartAt": "ec2InstanceQuarantineFn",
                  "States": {
                    "ec2InstanceQuarantineFn": {
                      "Type": "Task",
                      "Resource": "${ec2InstanceQuarantineFn.Arn}",
                      "End": true,
                      "Retry": [
                        {
                          "ErrorEquals": [
                            "States.ALL"
                          ],
                          "IntervalSeconds": 1,
                          "MaxAttempts": 3,
                          "BackoffRate": 2
                        }
                      ]
                    }
                  }
                }
              ]
            }
          }
        }

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - states.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSLambdaExecute"
        - "arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess"

  LambdaExecutionRoleAddonPolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
        PolicyName: IncidentResponseInfoSecPolicy
        PolicyDocument: 
            Statement: 
              - Sid: "SecurityGroupPolicy"
                Effect: "Allow"
                Action: 
                  - "ec2:RevokeSecurityGroupIngress"
                  - "ec2:DescribeSecurityGroupReferences"
                  - "ec2:RevokeSecurityGroupEgress"
                  - "ec2:ApplySecurityGroupsToClientVpnTargetNetwork"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:CreateSecurityGroup"
                  - "ec2:DescribeInstances"
                  - "ec2:CreateTags"
                  - "ec2:StopInstances"
                  - "ec2:CreateVolume"
                  - "ec2:CreateSnapshots"
                  - "ec2:CreateSnapshot"
                  - "ec2:DescribeSnapshots"
                  - "ec2:ModifyInstanceAttribute"
                Resource: '*'
        Roles: 
          - Ref: "LambdaExecutionRole"

  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: 
                  - Fn::GetAtt: [ ec2InstanceQuarantineFn, Arn ]
                  - Fn::GetAtt: [ ec2InstanceSnapshotFn, Arn ]

  CloudWatchEventRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "Rule to invoke state machine on GuardDuty Finding"
      EventPattern:
        source:
          - "aws.guardduty"
        detail:
          type:
          - "UnauthorizedAccess:IAMUser/InstanceCredentialExfiltration"
      Name: "Trigger_Qurantine_Ops"
      State: "ENABLED"
      Targets:
        -
          Arn: !Ref incidentResponseStepFunction
          Id: trigger_qurantine_ops_target
          RoleArn: !GetAtt CwExecuteStateMachineRole.Arn

  CwExecuteStateMachineRole:
    Type: "AWS::IAM::Role"
    Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Sid: "AllowCWEServiceToAssumeRole"
              Effect: "Allow"
              Action:
                - "sts:AssumeRole"
              Principal:
                Service:
                  - "events.amazonaws.com"
        Path: "/"
        Policies:
          -
            PolicyName: "ExecuteStateMachine"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action:
                    - "states:StartExecution"
                  Resource: !Ref incidentResponseStepFunction

  # Findings SNS Topic
  GuardDutySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: 'GDSNS'
      Subscription:
        -
          Endpoint: !Ref SecurityContactEmail
          Protocol: "email"
  GuardDutySNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: ID-GD-Topic-Policy
        Version: '2012-10-17'
        Statement:
        - Sid: SID-GD-Example
          Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action: sns:Publish
          Resource: !Ref GuardDutySNSTopic
      Topics:
      - !Ref GuardDutySNSTopic
